import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { generateKeyPair } from "@cambium/shared";

const envPath = resolve(process.cwd(), "../../.env");

const keys = generateKeyPair();

const banner = `# Generated by gen-demo-keys at ${new Date().toISOString()}.\n# DO NOT USE IN PRODUCTION — single demo signer, no rotation, no HSM.\n`;

const newLines = [
  banner,
  `DEMO_SIGNER_PRIVATE_KEY=${keys.privateKeyHex}`,
  `DEMO_SIGNER_PUBLIC_KEY=${keys.publicKeyHex}`,
  "",
].join("\n");

if (existsSync(envPath)) {
  const current = readFileSync(envPath, "utf8");
  // Remove any prior demo signer keys (keep everything else).
  const cleaned = current
    .split("\n")
    .filter(
      (l) =>
        !l.startsWith("DEMO_SIGNER_PRIVATE_KEY=") &&
        !l.startsWith("DEMO_SIGNER_PUBLIC_KEY=") &&
        !l.startsWith("# Generated by gen-demo-keys")
    )
    .join("\n");
  writeFileSync(envPath, cleaned.trimEnd() + "\n\n" + newLines);
} else {
  writeFileSync(envPath, newLines);
}

console.log("Wrote DEMO_SIGNER_PRIVATE_KEY and DEMO_SIGNER_PUBLIC_KEY to .env");
console.log("public:", keys.publicKeyHex);
